"""empty message

Revision ID: 2a85d67d1de0
Revises: 
Create Date: 2026-06-07 10:06:33.542565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a85d67d1de0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_guru_kelas_mapel'), 'guru_mengajar', type_='unique')
    op.create_unique_constraint('uq_guru_kelas_matapelajaran', 'guru_mengajar', ['guru_id', 'kelas_id', 'mata_pelajaran_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_guru_kelas_matapelajaran', 'guru_mengajar', type_='unique')
    op.create_unique_constraint(op.f('uq_guru_kelas_mapel'), 'guru_mengajar', ['guru_id', 'kelas_id', 'mata_pelajaran_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
